rematch/rematch

- src/effect.js
- test/effect.test.js
fixed effect test: "should be able to trigger another action w/ an object value"
> fixed effect test 

- test/effects.test.js
Removing an effects test that actually passes. 
Something weird is going on with jest here.
> Removing an effects test that actually passes. 

- .travis.yml
A basic travis setup to run unit tests on our code.
No code coverage implemented yet.
> closes #12. setup travis ci.

- src/dispatch.js
- src/init.js
- test/dispatch.test.js
> closes #3. use dispatch directly as store.dispatch

- README.md
- flow-typed/local/plugin.js
- package.json
- src/core.js
- src/init.js
- src/plugins/hooks.js
- test/config.test.js
- test/dispatch.test.js
- test/effects.test.js
- test/hooks.test.js
- test/init.test.js
- test/plugins.test.js
- test/select.test.js
- test/store.test.js
This is largely just a test to see if the CI is working.
It should run our unit tests before committing.
> Test coverage, plugin validation

- src/plugins/selectors.js
- test/select.test.js
> Removed autobind for selectors. Added tests with `reselect`

- .travis.yml
- README.md
- package-lock.json
- package.json
> setup coveralls

- README.md
> Revert "README: add comparison of redux & rematch"

- README.md
Much happier with this version.
Let me know what you think.
> add comparison of redux to readme

- README.md
I thought this section needed some work. A few goals in mind:
1) Convince people to switch dva or mirror
2) Convince people to choose rematch over other options
> README - expand on inspiration

- examples/react-redux-count/README.md
- examples/react-redux-count/package-lock.json
- examples/react-redux-count/package.json
- examples/react-redux-count/src/index.js
> fix example to work

- src/utils/validate.js
Fix crashing error in React Native.
> remove process.env validate check

- package-lock.json
- plugins/loading/package-lock.json
- plugins/loading/package.json
- plugins/loading/webpack.config.js
- plugins/persist/package-lock.json
- plugins/persist/package.json
- plugins/persist/webpack.config.js
- scripts/build.sh
- webpack.config.js
Removes a warning in console on web, crash in React Native.
> use production build of redux

- .babelrc
- .gitignore
- .travis.yml
- docs/plugins.md
- examples/react/count/package-lock.json
- package-lock.json
- package.json
- plugins/loading/.babelrc
- plugins/loading/package-lock.json
- plugins/loading/package.json
- plugins/loading/webpack.config.js
- plugins/persist/.babelrc
- plugins/persist/package-lock.json
- plugins/persist/package.json
- plugins/persist/webpack.config.js
- plugins/react-navigation/.babelrc
- plugins/react-navigation/.npmignore
- plugins/react-navigation/README.md
- plugins/react-navigation/package-lock.json
- plugins/react-navigation/package.json
- plugins/react-navigation/src/Navigator.js
- plugins/react-navigation/src/dispatch.js
- plugins/react-navigation/src/index.js
- plugins/react-navigation/src/reducer.js
- plugins/react-navigation/webpack.config.js
- scripts/build.sh
- src/plugins/effects.js
- webpack.config.js
> React-navigation plugin

- README.md
- package.json
- plugins/persist/examples/react-persist/package-lock.json
- plugins/persist/examples/react-persist/package.json
- plugins/persist/package-lock.json
- plugins/persist/package.json
- Fixes issues with tests being run on _book directory
- Fixes issues with readme title on wrong line
- Updates packages
> Basic fixes

- .gitignore
- .travis.yml
- examples/react/count/package-lock.json
- package.json
An attempt to fix the coveralls code coverage button in the README.
It's starting to get to me... ;)
> possible coverage fix

- SUMMARY.md
- docs/api.md
- docs/reduxApi.md
- plugins/updated/package-lock.json
- src/redux/reducers.ts
- src/redux/store.ts
- src/typings/rematch/index.d.ts
- src/utils/mergeConfig.ts
- test/store.test.js
References #177 & would close #168.
This PR so far only outlines the middleware with a failing test.
> redux.rootReducers -  a hook at reducers base that returns next state

- README.md
- examples/react/count/package-lock.json
- examples/react/count/package.json
- package-lock.json
- package.json
- rollup.config.js
Likely fixes #187.
Updates Rollup build. Adds Redux to build. +3kb.
> update rollup config. add redux to bundle

- README.md
Just made a quick and dirty todos example. Feel free to clean it up if needed!
> Add todos example to readme

- docs/plugins.md
- package-lock.json
- package.json
- plugins/persist/package.json
- plugins/persist/src/index.ts
- plugins/persist/test/persist.test.js
- test/dispatch.test.js
- test/effects.test.js
- test/init.test.js
Minor fixes, updates test coverage.
> full test coverage

- docs/api.md
> Update docs: api.md

- docs/purpose.md
> Update docs: purpose.md

- src/plugins/dispatch.ts
- test/dispatch.test.js
as discussed:
https://github.com/rematch/rematch/issues/208
> feat(effectPromiseValue): promises returned from effects resolve to the return value

- README.md
- SUMMARY.md
Docs were missing links to subscriptions & selectors.
> add missing plugins to README

- plugins/select/README.md
`select` should be from `@rematch/select`, not `@rematch/core`
> select should be from @rematch/select

- src/redux/store.ts
> fix issue with enhancers

- typings/rematch/index.d.ts
Some fixes for dispatch typings.
> Fix TypeScript Typings

- README.md
- docs/recipes/tests.md
Added small examples on how to test reducers and effects, examples available are by testing with store, or testing the functions directly. It has also a codesandbox example.
Please let me know if you want me to change anything.
> Added writing tests documentation #269

- README.md
- SUMMARY.md
- docs/recipes/testing.md
rename "tests" => "testing", add to gitbooks SUMMARY
> Polish testing docs

- CHANGELOG.md
- examples/react/count/package-lock.json
- examples/react/count/src/models.js
- package-lock.json
- package.json
- plugins/loading/test/loading-asBoolean.test.js
- plugins/loading/test/loading-asNumber.test.js
- src/init.ts
- src/model.ts
- src/plugins/dispatch.ts
- src/plugins/effects.ts
- src/utils/buildPlugins.ts
- test/dispatch.test.js
- test/effects.test.js
closes #300.
Effects are no longer firing as actions. This makes it quite hard to debug.
Work in Progress.
> effect actions not firing

- examples/ts/count/src/App.tsx
- examples/ts/count/src/models/dolphins.tsx
- examples/ts/count/src/models/sharks.tsx
- src/redux.ts
- typings/rematch/index.d.ts
Some additional fixes on top of @19majkel94's recent PR.
Updates example, and adds a fix for using TS v4.
> Additional typing fixes

- plugins/persist/README.md
`whiteList` doesn't exist. It should be `whitelist`
> Use correct redux-persist api

- .travis.yml
- package-lock.json
- package.json
> add bundlesize

- examples/react/count/package-lock.json
- package.json
- rollup.config.js
- scripts/bundles.js
- test/production.test.js
Closes #388.
CJS - dev/prod based on NODE_ENV
ESM - ES5 with sourcemaps
UMD - ES5 with sourcemaps
> create dev/prod builds

- .gitignore
- plugins/loading/index.d.ts
- plugins/loading/package-lock.json
- plugins/loading/package.json
- plugins/loading/rollup.config.js
> update rematch/loading ts build to use rollup-plugin-ts2

- docs/recipes/devtools.md
Add guide to support redux devtools for react-native
> Update devtools.md to support react-native

- src/pluginFactory.ts
- src/rematch.ts
Rematch initializes PluginFactory with a config
> PluginFactory exposes config.

- src/rematch.ts
- src/typings.d.ts
@d3dc - adds name to the store. 
Primarily for use in plugins.
> add name to store

- src/pluginFactory.ts
- src/rematch.ts
Reverts rematch/rematch#422
Until issues with typings can be resolved.
> Revert "PluginFactory exposes config."

- src/typings.d.ts
> add typings for global getState

- docs/api.md
- docs/recipes/testing.md
- plugins/react-navigation/README.md
- plugins/updated/examples/count/src/models.js
closes #472.
Remove references to global dispatch from old API
> cleanup references to global dispatch from old API

- plugins/immer/src/index.ts
Fixs https://github.com/rematch/rematch/issues/345
Much simplier than https://github.com/rematch/rematch/pull/490
> Fix immer plugin's cooperation with loading plugin

- examples/react/count/package-lock.json
- examples/react/count/package.json
- examples/react/multi-store/package.json
- rollup.config.js
closes #534.
Delivers a minified version of the "if prod -> min version else full" script. Webpack 4 was flagging these few lines as unminified code.
> resolve webpack 4 minification warnings

- src/typings.d.ts
> fix typings - boolean Action parameters requires Action<boolean, void>

- plugins/persist/src/typings.d.ts
> change @rematch/persist parameters to optional in declaration file

- plugins/select/package-lock.json
- plugins/select/package.json
It's a quick fix that fix a typo with package version 😄
> Fix warning about missing peer dependency

- package.json
Resolves https://github.com/rematch/rematch/issues/565#issuecomment-440131754
> license is MIT, not ISC

- examples/js/count/package.json
- plugins/immer/package.json
- plugins/loading-immutable/package.json
- plugins/loading/package.json
- plugins/persist/package.json
- plugins/react-navigation/package.json
- plugins/select/package.json
- plugins/subscriptions/package.json
- plugins/typed-state/package.json
- plugins/updated/package.json
Resolves follow up issue in #576.
Will also require minor updates to be published.
> Update plugin licenses to "MIT"

- docs/api.md
This PR fixes anchor links to headers with dots in them. 🎉
> fix docs/api.md anchors

- plugins/persist/package.json
> move rollup-plugin-typescript to devDependencies

- plugins/immer/README.md
Docs updated for avoid confusions.
https://github.com/rematch/rematch/issues/559
> Updated docs for rematch/inner

- docs/api.md
> Docs(api): mention factory interface for model effects declaration

- .prettierrc
closes #570. Parser had been using "flow"
> Set prettier parser to ts

- plugins/loading-immutable/src/index.ts
- plugins/loading/src/index.ts
Fixes isEffect tag loss in loading plugin.
> Keep isEffect tag

- examples/ts/count/src/models/dolphins.ts
- examples/ts/count/src/models/index.ts
- examples/ts/count/src/models/sharks.ts
- examples/ts/count/src/store.ts
- package-lock.json
- package.json
- src/typings/index.d.ts
1. More accurate type
1. Fix latest redux typing check error in typescript example
1. Add more type constrain in typescript example
related for issue #656
> fix: improved type checking & typescript example

- README.md
- docs/README.md
- docs/lang/zh-cn/README.md
> chore(): added slack badge

- README.md
- docs/_sidebar.md
https://github.com/rematch/rematch/issues/675
> fix(): fix docsify bad urls

- plugins/immer/CHANGELOG.md
- plugins/immer/package-lock.json
- plugins/immer/package.json
- plugins/immer/src/index.ts
- plugins/immer/tsconfig.json
> Update immer plugin from ^1.5.0 to ^4.0.0

- docs/api-reference/api.md
- docs/api-reference/pluginsapi.md
- docs/api-reference/reduxapi.md
Fixed all sections of api reference linking.
https://github.com/rematch/rematch/issues/691
> fix: fixed api reference section on docs

- src/typings/index.d.ts
> fix: fix type error while passing enum type to `RematchDispatcher` generics

- README.md
Noticed it wasn't working. This does the trick :D
> Fix Redux config options link in README

- docs/plugins/persist.md
should be:
```
const Root = () => (
<PersistGate persistor={persistor}>
<App />
</PersistGate>
)
```
not:
```
const Root = () => {
<PersistGate persistor={persistor}>
<App />
</PersistGate>
}
```
> docs/plugins/persist.md line[63] should Change bracket to parentheses

- docs/api/store.md
- docs/migration-guide.md
- examples/all-plugins-react-ts/src/models/cart.ts
- packages/core/src/dispatcher.ts
- packages/core/src/reduxStore.ts
- packages/core/src/rematchStore.ts
- packages/core/src/types.ts
- packages/core/test/dispatcher.test.ts
> feat: Introduced meta to action

- .github/ISSUE_TEMPLATE/bug_report.md
1. Add reproduce link section.
2. Use comment blocks for description.
> docs(issue-templ): add reproduce link section and use comment blocks for description.

- packages/core/src/rematchStore.ts
- packages/core/test/store.test.ts
for issue https://github.com/rematch/rematch/issues/872
> fix: context binding in addModel

- packages/core/package.json
- packages/immer/package.json
- packages/loading/package.json
- packages/persist/package.json
- packages/select/package.json
- packages/updated/package.json
> fix: updated peerDependencies

- examples/hooks-react-ts/src/index.tsx
- examples/hooks-react-ts/src/models/dolphins.ts
- examples/hooks-react-ts/src/models/sharks.ts
- packages/core/test/ts_typings/dispatcher-typings.test.ts
- packages/immer/test/immer.test.ts
- packages/select/src/index.ts
- packages/select/src/types.ts
- packages/updated/test/updated.test.ts
Co-authored-by: tianzhich <zhi.tian@yahoo.com>
> refactor: select typings without Record<string,any>

- examples/loading-react/src/App.js
Update loading example to show count change.
> chore: update loading example

- docs/typescript.md
The documentation is looking pretty good. I just think this is the line you actually meant to highlight.
> docs: highlight correct line

- docs/plugins/typed-state.md
- package.json
- packages/typed-state/README.md
- packages/typed-state/package.json
- packages/typed-state/src/index.ts
- packages/typed-state/test/typed-state.test.ts
- packages/typed-state/tsconfig.build.json
- packages/typed-state/tsconfig.json
- website/sidebars.js
I think it's a cool addition to javascript projects that want to get some safe access to his stores.
> feat: introduced @rematch/typed-state plugin

- docs/migrating/from-redux.md
Fix a minor typo in migrating doc
> docs: fix typo
