rematch/rematch

- src/dispatch.js
- src/index.js
- src/store.js
- test/dispatch.test.js
- test/effects.test.js
- test/index.test.js
Fixes #17 
@ShMcK 
Ran into some issues when trying to expose the store reference directly. 
The store was always resolving to null. This didn't work:
```js
// src/index.js
import { store } from './src/store'
export default {
store
}
```
So, I exposed it via a function: `getStore`. So the following works, all tests pass :)
```js
// src/index.js
import { getStore } from './src/store'
export default {
getStore
}
// elsewhere
import { getStore } from './src/index'
const store = getStore()
```
> Fixes #17 Expose store in public API

- .codeclimate.yml
setup [CodeClimate](https://codeclimate.com). No need to enable this until after the plugin API is completed.
> closes #16. add codeclimate

- src/effects.js
- test/effects.test.js
Progress with #7 .
Allows the following functionality:
```js
{
name: 'example',
state: 0,
reducers: {
addOne: (state) => state + 1
},
effects: {
callAddOne() {
// this references the local model dispatch
this.addOne()
}
}
}
```
Currently works with.
> add `this` context to effects

- src/plugins/dispatch.js
- src/plugins/effects.js
- test/dispatch.test.js
Dispatches now return a Promise.
This promise is handled in the "effects" middleware, so it can both wait until:
- an effect is completed
- a reducer is completed
> closes #10. add promise middleware to dispatches

- flow-typed/local/plugin.js
- src/core.js
- test/plugins.test.js
Now add a model to a plugin.
Question though: Would a plugin ever require more than one model? This current PR only allows a single model. This opens the question.... could your entire app be broken into a series of plugins?
You right now.
> closes #47. Add model option to plugin

- examples/react-redux-count/src/index.js
- src/plugins/selectors.js
- test/select.test.js
Selectors no longer needs state as the first param.
```js
// before:
select.a.b(state)
// after PR:
select.a.b() // automatically passes store in
```
See examples in "select.test.js"
> closes #50. Autobind selector to model state as first param

- src/core.js
- src/init.js
- src/model.js
- src/plugins/dispatch.js
- src/plugins/effects.js
- src/plugins/selectors.js
- src/plugins/subscriptions/index.js
- test/config.test.js
- test/dispatch.test.js
- test/effects.test.js
- test/init.test.js
- test/plugins.test.js
- test/store.test.js
Sets plugins as functions. 
```js
// AFTER
const plugin = (storeDispatch: $dispatch, config: $pluginConfig) => ({
onInit() {},                          // removed storeDispatch as param
onModel(model: $model) {}             // removed storeDispatch as param
middleware: (store) => (next) => (action) => {}
})
```
Currently there is a "storeDispatch" param passed in initially.
> Plugins api

- README.md
Adds a table comparing Redux & Rematch. I thought this was the most persuasive part of our presentation, so I stole it from your notes.
NOTE: The formatting may be messed up, I'm not sure if it will display correctly on Github. It's written in raw HTML in order to make a table with code blocks work. May need some editing as well.
Should look something like this, but hopefully with github styles:
> README: add comparison of redux & rematch

- README.md
- examples/react-redux-count/src/App.js
- examples/react-redux-count/src/index.js
- examples/react-redux-count/src/models.js
- plugins/loading/src/index.js
- plugins/loading/test/loading.test.js
- plugins/persist/test/persist.test.js
- src/core.js
- src/init.js
- src/model.js
- src/redux/reducers.js
- src/redux/store.js
- src/utils/getModels.js
- test/dispatch.test.js
- test/plugins.test.js
- test/select.test.js
- test/store.test.js
Issue
In the current build, dispatch & select aren't setup if you add it using the new `init({ models })` pattern. It seems `init` models aren't passed through the plugins pipeline.
I've added a failing test to demonstrate.
TODO
> update examples. demonstrate failing dispatch

- flow-typed/local/config.js
- package-lock.json
- src/redux/devtools.js
- src/redux/store.js
- test/config.test.js
closes #124 . Fixes broken redux devtools
Also allows users to pass in their own devtools config.
```js
init({
devtoolsConfig: {},
})
```
> fix redux devtools.

- src/plugins/subscriptions/create.js
- src/plugins/subscriptions/handlers.js
- src/plugins/subscriptions/index.js
- src/plugins/subscriptions/unsubscribe.js
- test/subscriptions.test.js
Closes #27. While "take" or "takeEvery", I think its a simpler API.
Sets up a way for users to unsubscribe from subscriptions.
```js
subscriptions: {
'second/addOne': (action, unsubscribe) => {
dispatch.first.addOne()
unsubscribe()
},
}
```
> Setup createUnsubscribe

- README.md
- examples/react/count/src/models.js
- src/plugins/effects.js
- test/effects.test.js
Passes a subset of exposed into effects.
```js
effects: {
doSomething(payload, getState) {
/* ... */
}
}
```
```js
effects: {
doSomething(payload, { dispatch, getState, select }) {
/* ... */
}
}
```
closes #125.
> pass exposed into effects.

- docs/api.md
- scripts/install.sh
- src/plugins/dispatch.js
- test/dispatch.test.js
closes #67.
```js
dispatch.count.addBy(1, { syncWithServer: true })
===
dispatch({ type: 'count/addBy', payload: 1, meta: { syncWithServer: true } })
```
> add meta option as second param in dispatch

- plugins/loading/README.md
- plugins/loading/package-lock.json
- plugins/loading/package.json
- plugins/loading/src/index.ts
- plugins/loading/test/loading.test.js
Can optimize loading plugin by specifying which actions to add show/hide indicators to.
Docs:
A shortlist of actions. Named with "modelName" & "actionName".
```js
{ whitelist: ['count/addOne'] })
```
A shortlist of actions to exclude from loading indicators.
```js
{ blacklist: ['count/addOne'] })
```
> add whitelist & blacklist to loading plugin

- src/plugins/effects.ts
- src/redux/reducers.ts
- test/dispatch.test.js
- typings/rematch/index.d.ts
rematch reducers signature is (state, payload) => state, 
whilst regular redux reducers signature is (state, action) => state
That make impossible for rematch reducers to access the 'meta' property of an action, a functionality that may be required in advanced scenarios (example: dynamic state paths)
A backward compatible solution could be, to pass a third parameter 'ReducerContext' to rematch reducers.
Initially, the ReducerContext include just whole action object, but in the future maybe it could host additional informations.
What do you think?
Thank you
> feat(meta): pass meta as third parameter to reducers

- README.md
- SUMMARY.md
Adds notes for migrating from Redux to Rematch with examples.
> closes #220. Add Migration guide

- docs/recipes/react.md
Since the created dispatchers don't rely on `this`, this works fine.
> React: explain destructuring dispatchers

- CHANGELOG.md
- docs/api.md
- package-lock.json
- package.json
- src/index.ts
- src/plugins/dispatch.ts
- src/redux/reducers.ts
- src/redux/store.ts
- src/utils/deprecate.ts
- src/utils/isListener.ts
- test/dispatch.test.js
- test/listener.test.js
- test/store.test.js
Closes #231. A question turned into a proposal.
Listeners should be able to capture actions for other models directly within reducers.
The implementation can change, it is still up for discussion and debate, just getting the ball rolling.
> Reducers that can listen to other model actions

- docs/purpose.md
From redux api docs: https://github.com/reactjs/react-redux/blob/master/docs/api.md#inject-todos-and-specific-action-creators-addtodo-and-deletetodo-with-shorthand-syntax
Closes #253.
> Change redux example in Purpose docs to use mapDispatchToProps shorthand

- README.md
- docs/recipes/vue.md
Hi,
I am the creator of [vuejs-redux](https://github.com/titouancreach/vuejs-redux). Vue/Redux binding that use scoped slots (native and documented feature of Vue). I forked the and edited the codesandbox to use my plugin and I added it in the readme. I'm not sure of the best integration in it.
> add example with vuejs-redux

- package-lock.json
- package.json
- plugins/loading/README.md
- plugins/loading/examples/react-loading-example/src/App.js
- plugins/loading/examples/react-loading-example/src/example.js
- plugins/loading/examples/react-loading-example/src/index.js
- plugins/loading/src/index.ts
- plugins/loading/test/loading-asBoolean.test.js
- plugins/loading/test/loading-asNumber.test.js
- plugins/loading/test/loading.test.js
I was having problems with the loading module resolving a pending effect too early, because out of a batch of dispatched effects, the first completed one set the loading state to `false`.
This implements an integer counter instead of a boolean value.
Also cleaned up the plugin tests slightly.
> loading plugin counts the number of outstanding effects per effect, module, and global

- src/init.ts
- src/utils/getActionCreators.ts
This PR adds action creators from each model to the Redux DevTools like so;
The action creators are generated from the reducers on the model;
```JavaScript
init({
models: {
counter: {
state: 0,
reducers: {
increment: (state, delta = 1) => state + delta,
decrement: (state, delta = -1) => state - delta,
}
}
}
});
```
This PR makes it so that we add an `actionCreators` property to `config.redux.devtoolOptions` (containing the action creators) if the `actionCreators` property isn't already defined.
Marked this as WIP as I'm looking for some feedback on the changes :smile:
> Add action creators to redux-devtools

- plugins/react-navigation/README.md
Adds a mini tutorial on how to add selectors to the model generated by the react-navigation plug-in.  This is useful for determining the current route name.
> Add documentation for using selectors with navigation plugin.

- plugins/select/README.md
- plugins/select/package-lock.json
- plugins/select/package.json
- plugins/select/src/index.ts
- plugins/select/test/select.test.js
This PR allows the `select` plugin to be compatible with an Immutable JS store. As a side effect, it also allows the user to pass the root state to the selectors if desired.
This PR adds a config option to the `select` plugin allowing the user to specify how to slice the root state before being passed to the selectors  The default preserves current functionality so this change is complete backward compatible.  However, by opening up this config, a user can configure this plugin to support Immutable JS or another type of store.
This PR partially addresses Issue #270 and Issue #302.
> Add support for Immutable JS in selector plugin.

- plugins/loading/README.md
- plugins/loading/package-lock.json
- plugins/loading/package.json
- plugins/loading/src/index.ts
- plugins/loading/test/loading-asBoolean-Immutable.test.js
- plugins/loading/test/loading-asNumber-Immutable.test.js
- plugins/loading/test/loading-asNumber.test.js
- plugins/loading/test/loading-modelConfig.test.js
These enhancements make the loading plugin compatible with Immutable JS.  Two functions are exposed in the config which allow the user to customize how the state is initialized and updated. This allows the user to use an Immutable JS or other store that is not a JavaScript object.
This enhancement further adds a `model` config which allows the user to add additional customization to the `loading` model.  Perhaps the most useful use-case would be adding `selectors` to the model.
> Enhance loading plugin for Immutable.

- plugins/react-navigation/README.md
- plugins/react-navigation/package-lock.json
- plugins/react-navigation/package.json
- plugins/react-navigation/src/Navigator.tsx
- plugins/react-navigation/src/index.ts
- plugins/react-navigation/src/redux.ts
This PR makes the react-navigation plugin compatible with Immutable JS.   The `sliceState` config  allows the user to configure how the navigation state can be found.  It also includes an example of how to use this plugin with Immutable JS.  There are no tests for this plugin but I did test the Immutable JS functionality on my own React Native app.
I would recommend testing for regression before merging.
It may just be my dev environment, but I could not get the package to compile without adding `"@types/react": "^16.1.0"`  to my `package.json` and removing `private` from the `Navigator` component's `render` method.   Those changes are not part of making this work for Immutable JS, but I could not compile without them.   Feel free to redact them if you see fit.
> Add stateSlice method to react-navigation plugin config.

- docs/recipes/devtools.md
The options should be passed down to `redux` object. Not on `init` object.
> Fix the documentation for DevTools options

- examples/ts/count/src/App.tsx
- examples/ts/count/src/models/sharks.tsx
- src/utils/mergeConfig.ts
Automatically adds store name to devtools. Largely for use with multiple stores.
```js
const store = init({
name: 'store-name',
})
```
Uses store.name as devtools.name
> v1 - Feature/add store name to devtools

- typings/rematch/index.d.ts
This PR fixes the signature of `RematchDispatch`.
Using union types is good for input, e.g. your function takes `number | string` as an argument.
But with polymorphic code that has overloads, the correct would be using intersection types.
In this case, the `dispatch` is both a dictionary with keys to model -> reducer, as well as a function that can take `Action` object. The typings fixes that, so now `dispatch.counter.increment(1);` compiles without errors 😉
> Fix RematchDispatch typings

- examples/ts/count/.gitignore
- examples/ts/count/package.json
- examples/ts/count/tsconfig.json
- package-lock.json
- package.json
- rollup.config.js
```
lib/index.js → dist/umd/rematch.prod.min.js, dist/cjs/rematch.prod.min.js, dist/esm/rematch.prod.min.js...
(!) Missing exports
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/smckay/Demos/rematch/node_modules/redux/es/redux.js
default is not exported by node_modules/redux/es/redux.js
1: import * as redux from "/Users/smckay/Demos/rematch/node_modules/redux/es/redux.js"; export default ( redux && redux['default'] ) || redux;
```
> Upgrade to Redux 4.0. 

- src/plugins/dispatch.ts
- src/plugins/effects.ts
- typings/rematch/index.d.ts
Closes #331.
Resolves an issue with @rematch/core v1.0.0-alpha.0+ where a warning would arise from Redux v4.
This was caused by an effect calling `getState` after it has been called. It could possibly lead to mutations, or async related issues.
Now getState for effects will be calculated on dispatch.
> getState in dispatch

- README.md
Importing the store to access the dispatch method would create circular imports in real life case, we should import the `dispatch` function from rematch directly.
> Update misleading store import example

- docs/recipes/typescript.md
- examples/ts/count/src/App.tsx
- examples/ts/count/src/store.ts
- typings/rematch/index.d.ts
Continuation of #357
Just a few more typescript improvements:
- Autocompletes store.dispatch
- Autocompletes store.getState() response
- Fixes store.subscribe return type
- Decrease the need of writing `typeof` everywhere
- Add link to counter example on TypeScript receipt
> TypeScript improvements on store object

- plugins/loading/src/index.ts
- plugins/loading/test/loading-asBoolean.test.js
- plugins/loading/test/loading-asNumber.test.js
Fix loading plugin regression regarding the issue #208
> fix(loadingEffectReturnValuePropagation): Propagate effect return value

- plugins/immer/tsconfig.json
Fixes #349.
See https://github.com/rematch/rematch/issues/349#issuecomment-389695117 for a better description of how this works.
I've run the unit tests against the module and it still seems to run fine.
I have not tested if this change affect the CommonJS and ES Module versions of the build, but it seems to fix the issue with the UMD version.
> Enable "esModuleInterop" TypeScript setting

- typings/rematch/index.d.ts
Due to the `sliceState` feature of `@rematch/select`, the state passed to selectors might be different from the model state, so it needs to be possible to define the shape of the selector input state separately.
For this reason, this changes the `Model<S = any>` type to `Model<S = any, SS = S>` and defines the selectors as `(state: SS, ...args: any[]) => any`.
> [TypeScript] Add independent selector state type parameter to Model<S>

- README.md
- examples/js/count/src/index.js
- examples/react/count/src/models.js
- examples/react/multi-store/src/containers/left/store.js
- examples/react/multi-store/src/containers/right/store.js
- examples/ts/count/src/models/dolphins.ts
- examples/ts/count/src/models/sharks.ts
- examples/ts/count/src/store.ts
- plugins/select/README.md
- plugins/select/index.d.ts
- plugins/select/src/index.ts
- src/index.ts
- test/store.test.js
- typings/rematch/index.d.ts
- [API] New `createModel` function for autocomplete purposes (https://github.com/rematch/rematch/issues/361#issuecomment-392510274)
- [API] New `getSelect` function for autocomplete purposes (https://github.com/rematch/rematch/pull/364#issuecomment-392596145)
- [API] New `getDispatch` function for autocomplete purposes (https://github.com/rematch/rematch/pull/369#issuecomment-391211890)
- [TYPINGS] Fix `RematchDispatch` `no compatible call signature` error
- [TYPINGS] Support `this` inside effects (alternative to #382)
I could not reproduce #361.
> TypeScript improvements - Part 3

- src/typings.d.ts
PS: Fix is on the [first commit](https://github.com/rematch/rematch/commit/43462e686b8347bf64558a206ca25399734f651d), the second one is just a refactoring (_I've split `ExtractRematchDispatchersFromModel` into smaller chunks_).
---
Fix error from #399:
`Argument of type 'number' is not assignable to parameter of type 'Action<void, void>'`
>  [typings] fix generic RematchDispatch

- examples/ts/count/tslint.json
- src/plugins/dispatch.ts
- src/plugins/effects.ts
closes #392.
Note, redux middleware blocks using state from dispatch.
> fix for rootstate. 

- package.json
`process.env.NODE_ENV` remains `undefined` in former situation.
This PR should fix the issue, and can be built to minified dist.
---
Love `rematch`, thanks for creating this framework.
> fix NODE_ENV in build script

- src/index.ts
- src/typings.d.ts
- src/utils/mergeConfig.ts
- tsconfig.json
Fix #406
@ShMcK can you finish this PR? It requires more knowledge about the internals.
Please run `npx tsc -p .` to see the remaining errors.
They are mostly because the `name` field it optional, so things like `this.reducers[model.name]` could cause an issue (`this.reducers[undefined]`). But can they really be undefined? Maybe the `name` field should be required instead of optional? Or are you setting the name automatically somewhere else?
> If you are pretty sure they will never be undefined for some reason, you can just add an `!`, e.g. `this.reducers[model.name!]`.
> Strict null check

- docs/recipes/devtools.md
- src/redux.ts
- src/typings.d.ts
Hey guys,
this PR is to allow redux devtools to be disabled. As per discussion here (https://github.com/rematch/rematch/issues/351), it's enabled by default, but can be disabled if needed. Please let me know what you think. Thanks!
> Allow to disable redux devtools

- plugins/loading/src/index.ts
- plugins/loading/test/loading-asBoolean.test.js
- plugins/loading/test/loading-asNumber.test.js
right now the `loading` plugin always resolve result even if we reject in the effect, it resolves with `undefined`
> [loading] don't always resolve result

- docs/pluginsApi.md
- src/plugins/dispatch.ts
- src/rematch.ts
- test/plugins.test.js
Returning an object from `onStoreCreated` will merge into the store.
This can be useful for plugins such as `select`, which are bound to a store.
Example:
```js
const pluginWithReturn = {
onStoreCreated: () => {
return {
returned: 42,
}
},
}
const store = init({
plugins: [pluginWithReturn],
})
expect(store.returned).toEqual(42)
```
> onStoreCreated return value with init

- README.md
`Github` is a typo, it should be `GitHub`.
> Fix typo: Github -> GitHub

- package.json
Without the scripts directory, postinstall can't run.
Running yarn, I get the following error:
```
error /home/millette/glassjaw-v5/node_modules/@rematch/core: Command failed.
Exit code: 1
Command:  node ./scripts/post_install.js
Arguments: 
Directory: /home/millette/glassjaw-v5/node_modules/@rematch/core
Output:
module.js:549
throw err;
^
Error: Cannot find module '/home/millette/glassjaw-v5/node_modules/@rematch/core/scripts/post_install.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
```
> Missing directory: scripts

- plugins/loading/index.d.ts
relative imports are currently breaking due to an incorrect path
> fix relative import of core typings in loading plugin

- src/typings.d.ts
add overloads to the function of createModel when Generic type M is not presented.
> Overloads createModel function when no ModelConfig

- plugins/persist/src/index.ts
I work with '_react-native-navigation_' and I need to know when the persistor has done its job without using the PersistorGate.
The callback added here does the trick.
> Persist Plugin: Optional callback when creating persistor.

- plugins/immer/README.md
The default version installed by `npm install @rematch/immer` was `0.1.0`, and it would get an error like [issues349](https://github.com/rematch/rematch/issues/349) with `rematch@next` installed.
> Update the npm install guide for @rematch/immer

- docs/recipes/redux.md
Plugins can have a middleware function without extending the redux ones.
> Quick Doc Fix: Redux Recipes

- plugins/select/README.md
- plugins/select/index.d.ts
- plugins/select/package-lock.json
- plugins/select/package.json
- plugins/select/src/index.ts
- plugins/select/test/select.test.js
- src/typings.d.ts
I typed a lot about the importance of dependency injection and getting data out of the state in #413.
The advantage I see to the current recommendation of "import your own selectors" is that you can declare inputs to selectors much more directly. All the select plugin currently does is remove control over that from you.
This PR seeks to make it more natural to handle the entire API of `reselect` inside the models.
First off, it imports `reselect` directly, and lets you override this through configuration. If we're imitating the `reselect` api, why not just be the `reselect` api?
Models are auto-wired with dependencies, completely decoupling them for testing:
```js
{
state: 1,
selectors: (slice, createSelector, hasProps) => ({
valueA () {
return slice(a => a)
},
valueB () {
return …
```
> Select plugin can also wire dependencies.

- examples/ts/count/package.json
- examples/ts/count/src/models/sharks.ts
- examples/ts/count/src/store.ts
- plugins/select/examples/cart/.gitignore
- plugins/select/examples/cart/README.md
- plugins/select/examples/cart/package.json
- plugins/select/examples/cart/public/index.html
- plugins/select/examples/cart/src/App.js
- plugins/select/examples/cart/src/index.js
- plugins/select/examples/cart/src/models.js
- plugins/select/examples/cart/src/store.js
This updates the examples to use `@rematch/select` 2.0.0.
closes #298
I added a selector to the react/count example since it shows `connect`. I can take that commit out if it should remain simple. (or make a new example)
> Select examples

- src/typings.d.ts
Hi guys,
There is an issue with type inference when effects access `rootState`. This is the same issue that's described here: https://github.com/rematch/rematch/issues/515
So type inferrence for this snippet will work:
```ts
const model = createModel({
/* omitted */
effects: dispatch => ({
async loadAsync(userId: string) {
/* omitted */
},
}),
})
```
But it will break for this one since we use `rootState`
```ts
const model = createModel({
/* omitted */
effects: dispatch => ({
async loadAsync(userId: string, rootState) {
/* omitted */
},
}),
})
```
The problem is in this declaration on the second to last line:
```ts
export type ExtractRematchDispatcherAsyncFromEffect<E> =
E extends () => Promise<void> ? RematchDispatcherAsync<void, void> :
E extends (payload: infer P) => Promise<void> ? …
```
> Fix typings issue for effects that use rootState

- src/typings.d.ts
return type in `effects` can be not only `void`
sometimes we need the return value from `effects`, so we will code like this:
```
// models/sample.ts
{
effects: {
async noPayloadWithReturnAsync() {
return {
res: 'noPayloadWithReturn'
}
},
}
} 
```
```
// somewhere.ts
dispatch.sample.noPayloadWithReturnAsync()
.then(ret => {
// do something with `ret.res`
})
```
in this PR, i allow the return type in `effects` not only `void`. 
The original will throw type error if you have return types except for `void`
there are bunch of issues about this: #398 #478 #520 #526 #515 
and i have tested all the cases on them
> fix typings in effects

- plugins/select/src/typings.d.ts
This PR fix the `Slicer` type signature (from Union `|` to Intersection `&`) and the type of `RematchStore` select property (missing `RootState` type in generic).
It also exports all the types as `@rematch/core` for further integration and own types extensions by consumers.
> Fix `Slicer` type and export select plugin types

- plugins/select/package-lock.json
- plugins/select/package.json
This just adds the ability to do `npm test` in `plugin/select`, since we can't re #544 - v1.0 of core removed running plugin tests.
I copy and pasted the same coverage configuration to the plugin config, but didn't do anything with it. Is there anything to do to include plugin coverage in Travis?
Is this the intended way to do plugin tests since the change?
> Add jest and config to select plugin

- plugins/select/README.md
Fix documentation example since `re-reselect` doesn't export a `createCachedSelector` named export (but it might be a good idea for the future 😃)
> Fix mistaken re-reselect example on docs

- docs/recipes/typescript.md
Should fix #589 - relative paths under `/docs` will be _relative to gitbooks.io_
> make the github link absolute in typescript recipe

- docs/recipes/typescript.md
Just updating docs for being in the same line that actual versions.
148e810#diff-adfd610834090020180c37221296a7e0
This fixes this: https://github.com/rematch/rematch/issues/622, that was related to other issue closed about getSelect was undefined.
> (fix): select auto complete import docs

- docs/api-reference/api.md
- Added section to `api.md` docs that explain the order in which effects and reducers with the same name are executed
Behavior from [src/plugins/effects.ts](https://github.com/rematch/rematch/blob/master/src/plugins/effects.ts#L56)
> Docs (api.md) effect with same name as reducer

- plugins/select/rollup.config.js
The umd build for reselect library exposes the lib with capital letter, i.e. `Reselect`, which means current UMD build is broken.
> fix global variable name for reselect

- plugins/subscriptions/src/handlers.ts
previous escapeRegex would only replace the first occurrence of '*'.
> Fix escape all string

- docs/recipes/devtools.md
Reactotron had a breaking change removing `createStore` in favor of `createEnhancer()` which now has to be defined on the `enhancers` array instead of the `createStore` function. For typescript with strict typing a null assertion is needed since the type can return undefined.
> Update Reactotron/Rematch Integration

- plugins/loading/src/index.ts
Hi, 
Rematch newcomer here!
I'm using Typescript, and would like to use the loading plugin.
However, because the loading model is added with the plugin api, the AppState (`RematchRootState<typeof models>`) type doesn't know about the loading state.
I've added it in the plugin, to be able to import it and use it directly: 
`export type AppState = RematchRootState<typeof models> & LoadingState<typeof models>`
I use the type on my side, but share it with the community, as I think it can interest.
Thanks for this cool package,
Matt'.
> Add LoadingState type.

- plugins/persist/src/typings.d.ts
The config is not required, as it has a `{}` default.
> Fix persist config typing.

- src/typings/index.d.ts
Hi, 
This PR fix the typings for the dispatcher.
When dispatching an action, the result will not be a promise of the action, but the return type of the effects.
Example: 
Considering:
```ts
export const contactsModel = createModel({
name: 'contacts',
reducers: {...}
effects: {
async create(payload: ContactCreationPayload): Promise<Contact> {
const contact = await contactCreationCall(payload)
this.addOrUpdate(contact)
return contact
},
async fetchAll() {
const contacts = await contactsListFetchingCall()
this.updateAll(contacts)
},
},
})
```
The type of foo in: 
```ts
async function () {
const foo = await store.dispatch.contacts.create({} as ContactCreationPayload)
}
```
should be Contact. 
Before this PR, it was `Action<any, any>`, but the object is really of type Contact and a …
> Fix dispatcher typing.

- src/typings/index.d.ts
Hi! I've been having type issues with the createModel with it returning different types due to it be duplicated in the `index.d.ts` I removed the duplication and that fixes the error.
> Removed duplicate createModel function in type decleration

- docs/recipes/typescript.md
- examples/ts/count/src/models/dolphins.ts
- examples/ts/count/src/models/index.ts
- examples/ts/count/src/models/sharks.ts
- examples/ts/count/src/store.ts
- examples/ts/hooks/src/models/dolphins.ts
- examples/ts/hooks/src/models/index.ts
- examples/ts/hooks/src/models/sharks.ts
- examples/ts/hooks/src/store.ts
- src/typings/index.d.ts
Fix #723
Fix effect dispatcher type. When declaring and effect like (payload, state) => {} the state type was infered as meta type.
> Fix incorrect typings

- examples/gatsby-example/gatsby-config.js
- examples/gatsby-example/package.json
- examples/gatsby-example/src/pages/index.tsx
Removes the duplicate Provider. It is already in `src/wrapper.tsx`, which wraps _all_ pages rendered by SSR and in-browser, so the one on `src/pages/index.tsx` may be omitted.
Also adds types for react-redux
And removes the references to src/images, which was preventing the build from starting
Closes last posed question in #807
> Fix gatsby example

- docs/examples.md
Currently it refers to: https://github.com/rematch/rematch/examples which returns a 404.
Not sure if this should point to the next or master branch, but it seems most library refer to the newer one of the two.
> Docs Fix URL for "examples" page

- examples/hooks-react-ts/src/App.tsx
- examples/hooks-react-ts/src/models/dolphins.ts
- packages/core/src/types.ts
In my project, I came across the following scenario. 
I have a shared store that controls whether a global loading icon should show/hide. The global loading components supports an optional text.
Obviously, I call two reducers for each store field.  I'm thinking if we can do
```javascript
dispatch.globalLoading.show();  // only show loading icon
dispatch.globalLoading.show('Please wait...') // show loading icon with text
```
which is more simple and easy to use(in my opinion) 😃
> feat: support optional payload parameter on reducer

- docs/plugins/loading.md
- docs/plugins/select.md
- docs/plugins/updated.md
- examples/all-plugins-react-ts/src/AppWithoutHooks.tsx
- examples/all-plugins-react-ts/src/models/cart.ts
- examples/all-plugins-react-ts/src/models/index.ts
- examples/all-plugins-react-ts/src/models/players.ts
- examples/all-plugins-react-ts/src/store.ts
- packages/core/src/index.ts
- packages/core/src/reduxStore.ts
- packages/core/src/rematchStore.ts
- packages/core/src/types.ts
- packages/select/package.json
- packages/select/src/index.ts
- packages/select/src/types.ts
- packages/select/test/select.test.ts
- selectors on model has three props, we must guarantee it doesn't have errors:
```jsx
const selection = store.select(models => ({
// todo: this isn't getting autocompleted
total: models.cart.total,
}))
```
```jsx
const mapState = (state: RootState) => ({
settingsState: state.settings,
loadingState: state.loading,
playersState: state.players,
// todo: props shouldn't be required
...selection(state, null)
})
```
```jsx
// todo: we must type the props autocomplete of the selector new values
type Props = StateProps & DispatchProps
```
```jsx
// todo: we must type the props autocomplete of the selector new values
type Props = StateProps & DispatchProps
```
> fix: @rematch/select typescript plugin compatibility

- docs/plugins/loading.md
- packages/loading/src/index.ts
- packages/loading/test/loading-asNumber.test.ts
The `loading` state value has a `boolean` type even when `asNumber` is enabled.
Add an optional parameter to `ExtraModelsFromLoading` to let the developer specify whether `asNumber` is enabled.
> fix(loading): fix ts type when asNumber enabled

- docs/quick-start.md
When I refer to the TypeScript sample code, I found there is a missing variable in `import { RootState, Dispatch } from './store'` statement. so...it is suggested to add it :)
> fix: add missing variable for import statement

- packages/core/src/reduxStore.ts
Decreased more the size of core library, doing this we remove a polyfill used in IE11 :)
> fix: Reduced @rematch/core bundle-size

- packages/immer/src/index.ts
- packages/immer/test/immer.test.ts
Specifying arrays of `whitelist` and/or `blacklist` models in `immerPlugin` constructor was being ignored.
I've made a fix and added test cases.
> fix: immer `whitelist` and `blacklist` conf no longer ignored

- packages/select/src/types.ts
- packages/select/test/select.test.ts
This should fix structured selector typing where executing a structured selector returned the correct selector values, but typescript indicated that the values are actually selectors. See #866 for more info.
I updated an existing test case that explicitly defines expected return types.
> fix: @rematch/select structured selector typing (#866)

- docs/introduction.md
If you in [docs](https://rematchjs.org/docs/), and then click plugin hyperlink in **Composable Plugins**. After that, your current location is `https://rematchjs.org/docs/plugins`. Finally, click the plugin list such as **Immer Plugin** hyperlink, you will get `Page Not Found`.
> docs: fix immer plugin href

- packages/core/src/bag.ts
- packages/core/src/types.ts
https://github.com/rematch/rematch/pull/891/files#diff-1f8711ffcf4ef0b26aea69d164072937102d5109ecfd8790b6e879c7421e00d3
Since I've checked how it's the strategy with typescript and `addModel`, has sense to define a RootModel which is Partial<T> of a complete RootModel.
```ts
import { Models } from '@rematch/core'
import { players } from './players'
import { settings } from './settings'
import { cart } from './cart'
export interface RootModel extends Models<RootModel> {
players: typeof players
cart: typeof cart
settings: typeof settings
}
export const models: Partial<RootModel> = { players, cart }
```
In this way we can define the complete typings but a FUTURE usage, but the current models isn't complete yet.
> fix: make models on init() Partial<T>

- packages/core/src/types.ts
- packages/core/test/ts_typings/circular-references.test.ts
- packages/core/test/ts_typings/dispatcher-typings.test.ts
Related to #901 
Introduces a new test to avoid regression with dispatcher system:
- Reducers
- With optional payload
- With required payload
- Effects
- With optional payload
- With required payload
- With optional payload and rootState
- With required payload and required rootstate
> fix: optional payload inference inside effects

- packages/core/src/types.ts
- packages/core/test/ts_typings/circular-references.test.ts
- packages/core/test/ts_typings/dispatcher-typings.test.ts
1. Simplify the `ExtractRematchDispatcherFromReducer` type alias.  
2. Make the Inference of the optional payload (and meta) correctly.
> fix: optional payload inference

- .github/workflows/ci.yml
- .github/workflows/next-typescript-ci.yml
Will close #895
Also we get rid of setup-node@v2-beta, already it's stable with @v2
> ci: added nightly builds for testing typescript next

- examples/hooks-react-ts/src/index.tsx
- examples/hooks-react-ts/src/models/dolphins.ts
- examples/hooks-react-ts/src/models/sharks.ts
- packages/core/src/bag.ts
- packages/core/src/config.ts
- packages/core/src/dispatcher.ts
- packages/core/src/index.ts
- packages/core/src/reduxStore.ts
- packages/core/src/rematchStore.ts
- packages/core/src/types.ts
- packages/core/src/validate.ts
- packages/core/test/plugins.test.ts
- packages/core/test/ts_typings/circular-references.test.ts
- packages/core/test/ts_typings/dispatcher-typings.test.ts
- packages/core/test/validatePlugins.test.ts
- packages/immer/src/index.ts
- packages/immer/test/immer.test.ts
- packages/loading/test/loading-asBoolean.test.ts
- packages/loading/test/loading-asNumber.test.ts
- packages/persist/src/index.ts
- packages/select/src/index.ts
- packages/select/src/types.ts
- packages/updated/src/index.ts
- packages/updated/test/updated.test.ts
There are some fixes or improvements related to the rematch type system. If you have any issues you can checkout a branch from the `improve-typing` and create a PR and set `improve-typing` as merge target.
> refactor: improve type system

- jest.config.js
- packages/loading/src/index.ts
- testsetup.js
Return the chain promise to propagate the throw error and continue the chaining normally. 
Fix the Unhandled Promise Rejection
Closes #906
> fix: loading plugin returns chain of promises effect

- packages/core/src/types.ts
- packages/core/test/config.test.ts
- packages/core/test/dispatcher.test.ts
- packages/core/test/listener.test.ts
- packages/core/test/multiple.test.ts
- packages/core/test/plugins.test.ts
- packages/core/test/store.test.ts
- packages/core/test/ts_typings/dispatcher-typings.test.ts
Resolves #912 
Before 4.3 TypeScript accepted "duplicated" types but now is more stricter, so we just merge them giving priority always to reducers because is the entrypoint (will be the first executed if the same is duplicated)
> fix: reducers and effects with same name are correctly typed 4.3.X

- .github/workflows/next-typescript-ci.yml
- blog/2021-02-01-welcome.md
- docs/installation.md
- docs/migrating/from-v1-to-v2.md
- docs/typescript.md
- examples/all-plugins-react-ts/README.md
- examples/all-plugins-react-ts/public/index.html
- examples/count-react-ts/README.md
- examples/count-react-ts/public/index.html
- examples/hooks-react-ts/README.md
- examples/hooks-react-ts/public/index.html
- website/src/components/MultiLangComponent.tsx
- website/src/pages/index.tsx
Nice work with the twoslash code samples, I switched all the user-facing cases of "Typescript" to "TypeScript" ( [from here](https://www.typescriptlang.org/branding/))
> chore: convert Typescript to TypeScript

- docs/plugins/loading.md
- examples/all-plugins-react-ts/src/__snapshots__/index.test.tsx.snap
- examples/all-plugins-react-ts/src/index.test.tsx
- examples/all-plugins-react-ts/tsconfig.json
- package.json
- packages/loading/src/index.ts
- packages/loading/test/loading-asDetailed.test.ts
- packages/loading/test/loading-asFull.test.ts
- packages/loading/test/loading-asNumber.test.ts
- website/docusaurus.config.js
- website/package.json
- yarn.lock
Finally found some time to work on this cool feature.
This introduces a little breaking change (which is not, because under the hood adapts the configuration to match the newest one if users are using the old one)
Basically now @rematch/loading plugin accepts a `type` property (By default is type: boolean)
This property accepts: `'number'`, `'boolean'`, `'full'`
Basically returns `{ success: false, loading: true, error: false }`, if the effect promise returns an error the error response is added to error.
Works fine with Typescript as far as I could check.
Will resolve #877
> feat: @rematch/loading with type: 'full' returns success/error/loading

- docs/api-reference/index.md
Swaped bullet points in api documentation with tables @semoal
> docs: replaced bullet points in api docs with table

- packages/immer/src/index.ts
- packages/immer/test/immer.test.ts
By the way, why we treat primitive different from object value? I think the default behavior is ok.
> fix: immer behaves unexpectedly when model state is a nullable primitive value

- docs/plugins/immer.md
... since it's a required peer dependency.
> docs: Add immer to installation command

- packages/core/src/dispatcher.ts
- packages/core/src/rematchStore.ts
- packages/core/test/v1_regressions/circurlarmodels.test.ts
Fixes #811
Short version of this problem given below 
```js
/**---Problem---**/
const dispatch = {};
const gen = ({ a, b }) => {
return {
log: () => {
console.log(a, b);
}
};
};
["a", "b"].forEach((item) => {
const x = {};
dispatch[item] = x;
x['run' + item] = gen(dispatch);
});
dispatch["a"].runa.log();
dispatch["b"].runb.log();
/**--- Solution ---**/
const dispatch = {
a: {},
b: {}
};
const gen = ({ a, b }) => {
return {
log: () => {
console.log(a, b);
}
};
};
["a", "b"].forEach((item) => {
const x = dispatch[item] || {};
dispatch[item] = x;
x['run' + item] = gen(dispatch);
});
dispatch.a.runa.log();
dispatch.b.runb.log();
```
```sh
{ runa: { log: [Function: log] } } undefined
{ runa: { log: [Function: log] } } { runb: { log: [Function: log] } }
{ runa: { log: [Function: log] } } { …
```
> fix: circular reference destructuring works with all models
